// <auto-generated />
using System;
using HW5NoteKeeper.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HW5NoteKeeper.Data.Migrations
{
    [DbContext(typeof(NoteKeeperContext))]
    partial class NoteKeeperContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HW5NoteKeeper.Models.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset>("CreatedDateUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedDateUtc");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("details");

                    b.Property<DateTimeOffset?>("ModifiedDateUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ModifiedDateUtc");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("summary");

                    b.Property<string>("UserRealmId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UserRealmId");

                    b.HasKey("Id");

                    b.HasIndex("UserRealmId");

                    b.ToTable("NoteMultiTenant", (string)null);
                });

            modelBuilder.Entity("HW5NoteKeeper.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Name");

                    b.Property<Guid>("NoteId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("NoteId");

                    b.HasKey("Id");

                    b.HasIndex("NoteId");

                    b.ToTable("Tag", (string)null);
                });

            modelBuilder.Entity("HW5NoteKeeper.Models.Tag", b =>
                {
                    b.HasOne("HW5NoteKeeper.Models.Note", "Note")
                        .WithMany("Tags")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");
                });

            modelBuilder.Entity("HW5NoteKeeper.Models.Note", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
